/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2022-05-23

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "stm32f4xx_rcc.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_tim.h"
#include "stm32f4xx_adc.h"
#include "stm32f4xx_usart.h"
#include "misc.h"
/* Private macro */

enum _state {
	MODE_OFF = 0,
	MODE_1 = 1,
	MODE_2 = 2
} State;


/* Private variables */
static uint8_t state = MODE_1;
unsigned int convert_code = 0;

/* Private function prototypes */
static void button_init(void);
static void mode_1_init(void);
static void mode_2_init(void);
static void usart_init(void);

static void mode_1_deinit(void);
static void mode_2_deinit(void);

static void mode_1_process(void);
static void mode_2_process(void);


static void mode_timer_init1();
static void mode_timer_init2();

void analizator_adc_init(void);
void analizator_init(void);
u16 readADC1(u8 channel);
void check_cmd(uint8_t ch);
void Usart_Log(uint8_t * buf);

void TIM2_IRQHandler(void)
{
	if (TIM_GetITStatus(TIM2, TIM_IT_Update) != RESET) {
		TIM_ClearITPendingBit(TIM2, TIM_IT_Update);
		//анализ состояния кнопки
		if(GPIO_ReadInputDataBit(GPIOA, GPIO_Pin_0) == 0) {
			Usart_Log("Analizing button\n");
			switch (state) {
				case MODE_OFF:
					state = MODE_1;
					break;
				case MODE_1:
					mode_1_deinit();
					state = MODE_2;
					break;
				case MODE_2:
					mode_2_deinit();
					state = MODE_1;
					break;
				default:
					break;
			}
		}
		//мигание светодиодов
		switch (state) {
		    Usart_Log("Мигание светодиодов\n");
			case MODE_OFF:
				break;
			case MODE_1:
				GPIO_ToggleBits(GPIOD, GPIO_Pin_12);
				break;
			case MODE_2:
				GPIO_ToggleBits(GPIOD, GPIO_Pin_13);
				break;
			default:
				break;
		}

	}
}

void TIM6_IRQHandler(void)
{
	if (TIM_GetITStatus(TIM6, TIM_IT_Update) != RESET)
	{
		TIM_ClearITPendingBit(TIM6, TIM_IT_Update);
		if(MODE_1 == state)
		{
			//get value from ADC1 channel 1
		    Usart_Log("Get value from ADC1 channel 1\n");
			convert_code = readADC1(ADC_Channel_1);
		}
		else if(MODE_2 == state)
		{
			//get value from ADC1 channel 2
		    Usart_Log("Get value from ADC1 channel 2\n");
			convert_code = readADC1(ADC_Channel_2);
		}
	}
}

void USART1_IRQHandler(void){

	if( USART_GetITStatus(USART1, USART_IT_RXNE) )
	{
	    Usart_Log("GetITStatus\n");
		USART_ClearITPendingBit(USART1, USART_IT_RXNE);
		uint8_t t = USART_ReceiveData(USART1);
		check_cmd(t);

	}

}


/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
  usart_init();
  button_init();
  mode_1_init();
  mode_2_init();
  analizator_init();

  while (1)
  {
	switch (state) {
		case MODE_OFF:
			break;
		case MODE_1:
			mode_1_process();
			break;
		case MODE_2:
			mode_2_process();
			break;
		default:
			break;
	}
  }
}

/* Private functions */
static void mode_1_deinit(void)
{
    Usart_Log("Reset Bits Pin 12\n");
	GPIO_ResetBits(GPIOD, GPIO_Pin_12);
}

static void mode_2_deinit(void)
{
    Usart_Log("Reset Bits Pin 13\n");
	GPIO_ResetBits(GPIOD, GPIO_Pin_13);
}

static void button_init(void)
{
	Usart_Log("Init Button\n");
	GPIO_InitTypeDef gpioConf;
	//инициализация входа, подключенного к кнопке
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
	gpioConf.GPIO_Pin = GPIO_Pin_0;
	gpioConf.GPIO_Mode = GPIO_Mode_IN;
	GPIO_Init(GPIOA, &gpioConf);
}

static void usart_init(void)
{
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_USART1, ENABLE);

	GPIO_InitTypeDef GPIO_InitStruct;
	GPIO_InitStruct.GPIO_Pin = GPIO_Pin_9 | GPIO_Pin_10;
	GPIO_InitStruct.GPIO_Mode = GPIO_Mode_AF;
	GPIO_InitStruct.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStruct.GPIO_OType = GPIO_OType_PP;
	GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_Init(GPIOA, &GPIO_InitStruct);

	GPIO_PinAFConfig(GPIOA, GPIO_PinSource9, GPIO_AF_USART1);
	GPIO_PinAFConfig(GPIOA, GPIO_PinSource10, GPIO_AF_USART1);

	USART_InitTypeDef USART_InitStruct;
	USART_InitStruct.USART_BaudRate = 115200;
	USART_InitStruct.USART_WordLength = USART_WordLength_8b;
	USART_InitStruct.USART_StopBits = USART_StopBits_1;
	USART_InitStruct.USART_Parity = USART_Parity_No;
	USART_InitStruct.USART_HardwareFlowControl = USART_HardwareFlowControl_None;
	USART_InitStruct.USART_Mode = USART_Mode_Rx | USART_Mode_Tx;
	USART_Init(USART1, &USART_InitStruct);

	NVIC_InitTypeDef NVIC_InitStructure;
	USART_ITConfig(USART1, USART_IT_RXNE, ENABLE);
	NVIC_InitStructure.NVIC_IRQChannel = USART1_IRQn;
	NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 0;
	NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0;
	NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
	NVIC_Init(&NVIC_InitStructure);
	USART_Cmd(USART1, ENABLE);

    Usart_Log("USART Init\n");

}

static void mode_1_led_init(void)
{
	Usart_Log("MODE 1 led Init\n");

	GPIO_InitTypeDef gpioConf;
	//инициализация входа, подключенного к светодиоду
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE);
	gpioConf.GPIO_Pin =  GPIO_Pin_12;
	gpioConf.GPIO_Mode = GPIO_Mode_OUT;
	gpioConf.GPIO_Speed = GPIO_Speed_100MHz;
	gpioConf.GPIO_OType = GPIO_OType_PP;
	gpioConf.GPIO_PuPd = GPIO_PuPd_NOPULL;
	GPIO_Init(GPIOD, &gpioConf);
}

static void mode_timer_init1(void)
{
	Usart_Log("MODE timer init 1\n");

	//config NVIC
	NVIC_InitTypeDef nvic_struct;
	nvic_struct.NVIC_IRQChannel = TIM2_IRQn;
	nvic_struct.NVIC_IRQChannelPreemptionPriority = 0;
	nvic_struct.NVIC_IRQChannelSubPriority = 1;
	nvic_struct.NVIC_IRQChannelCmd = ENABLE;
	NVIC_Init(&nvic_struct);

	//congig TIM2
	TIM_TimeBaseInitTypeDef tim_struct;
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);
	TIM_Cmd(TIM2, DISABLE);
	tim_struct.TIM_Period = 3000-1 ;
	tim_struct.TIM_Prescaler = 4200 -1;
	tim_struct.TIM_ClockDivision = 0;
	tim_struct.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_TimeBaseInit(TIM2, &tim_struct);
	TIM_ITConfig(TIM2, TIM_IT_Update, ENABLE);
	TIM_Cmd(TIM2, ENABLE);
}


static void mode_timer_init2(void)
{
	Usart_Log("MODE timer init 2\n");
	//config NVIC
	NVIC_InitTypeDef nvic_struct;
	nvic_struct.NVIC_IRQChannel = TIM2_IRQn;
	nvic_struct.NVIC_IRQChannelPreemptionPriority = 0;
	nvic_struct.NVIC_IRQChannelSubPriority = 1;
	nvic_struct.NVIC_IRQChannelCmd = ENABLE;
	NVIC_Init(&nvic_struct);

	//congig TIM2
	TIM_TimeBaseInitTypeDef tim_struct;
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);
	TIM_Cmd(TIM2, DISABLE);
	tim_struct.TIM_Period = 6000-1 ;
	tim_struct.TIM_Prescaler = 4200 -1;
	tim_struct.TIM_ClockDivision = 0;
	tim_struct.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_TimeBaseInit(TIM2, &tim_struct);
	TIM_ITConfig(TIM2, TIM_IT_Update, ENABLE);
	TIM_Cmd(TIM2, ENABLE);
}

static void mode_pwm_init(void)
{
	Usart_Log("MODE pwm init\n");
	GPIO_InitTypeDef gpio_init;
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE);
	gpio_init.GPIO_Pin = GPIO_Pin_14 | GPIO_Pin_15;
	gpio_init.GPIO_Mode = GPIO_Mode_AF;
	gpio_init.GPIO_Speed = GPIO_Speed_100MHz;
	gpio_init.GPIO_OType = GPIO_OType_PP;
	gpio_init.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_Init(GPIOD, &gpio_init);

	GPIO_PinAFConfig(GPIOD, GPIO_PinSource14, GPIO_AF_TIM4);
	GPIO_PinAFConfig(GPIOD, GPIO_PinSource15, GPIO_AF_TIM4);

	TIM_TimeBaseInitTypeDef time_init;
	TIM_OCInitTypeDef oc_init;
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM4, ENABLE);
	uint16_t PrescalerValue = (uint16_t)((SystemCoreClock / 2) / 21000000);
	time_init.TIM_Period = 4095;
	time_init.TIM_Prescaler = PrescalerValue;
	time_init.TIM_ClockDivision = 0;
	time_init.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_TimeBaseInit(TIM4, &time_init);

	oc_init.TIM_OCMode = TIM_OCMode_PWM1;
	oc_init.TIM_OutputState = TIM_OutputState_Enable;
	oc_init.TIM_Pulse = 0;
	oc_init.TIM_OCPolarity = TIM_OCPolarity_High;

	TIM_OC3Init(TIM4, &oc_init);
	TIM_OC3PreloadConfig(TIM4, TIM_OCPreload_Enable);

	oc_init.TIM_OutputState = TIM_OutputState_Enable;
	oc_init.TIM_Pulse = 0;
	TIM_OC4Init(TIM4, &oc_init);
	TIM_OC4PreloadConfig(TIM4, TIM_OCPreload_Enable);

	TIM_ARRPreloadConfig(TIM4, ENABLE);
	TIM_Cmd(TIM4, ENABLE);

}

static void mode_1_init(void)
{
	Usart_Log("MODE 1 init\n");
	mode_1_led_init();
	mode_timer_init1();
	mode_pwm_init();
}

static void mode_2_led_init(void)
{
	Usart_Log("MODE 2 led Init\n");
	GPIO_InitTypeDef gpioConf;
	//инициализация входа, подключенного к светодиоду
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE);
	gpioConf.GPIO_Pin =  GPIO_Pin_13;
	gpioConf.GPIO_Mode = GPIO_Mode_OUT;
	gpioConf.GPIO_Speed = GPIO_Speed_100MHz;
	gpioConf.GPIO_OType = GPIO_OType_PP;
	gpioConf.GPIO_PuPd = GPIO_PuPd_NOPULL;
	GPIO_Init(GPIOD, &gpioConf);
}


static void mode_2_init(void)
{
	Usart_Log("MODE 2 init\n");
	mode_2_led_init();
	mode_timer_init2();
	mode_pwm_init();
}

static void mode_1_process(void)
{
	Usart_Log("MODE 1 process\n");
	TIM4->CCR3 = convert_code;
}

static void mode_2_process(void)
{
	Usart_Log("MODE 2 process\n");
	TIM4->CCR4 = convert_code;
}

//analizator
static void analizator_timer_init(void)
{
	Usart_Log("Init Tim5\n");
	//config NVIC
	NVIC_InitTypeDef nvic_struct;
	nvic_struct.NVIC_IRQChannel = TIM5_IRQn;
	nvic_struct.NVIC_IRQChannelPreemptionPriority = 0;
	nvic_struct.NVIC_IRQChannelSubPriority = 1;
	nvic_struct.NVIC_IRQChannelCmd = ENABLE;
	NVIC_Init(&nvic_struct);

	//congig TIM2
	TIM_TimeBaseInitTypeDef tim_struct;
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM5, ENABLE);
	TIM_Cmd(TIM5, DISABLE);
	tim_struct.TIM_Period = 2500-1 ;
	tim_struct.TIM_Prescaler = 4200 -1;
	tim_struct.TIM_ClockDivision = 0;
	tim_struct.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_TimeBaseInit(TIM5, &tim_struct);
	TIM_ITConfig(TIM5, TIM_IT_Update, ENABLE);
	TIM_Cmd(TIM5, ENABLE);
}

void analizator_adc_init(void) {
	Usart_Log("Analizator ADC init\n");
	//configure gpio for channel1
	GPIO_InitTypeDef gpio;
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
	GPIO_StructInit(&gpio);
	gpio.GPIO_Pin = GPIO_Pin_1;
	gpio.GPIO_Mode = GPIO_Mode_AN;
	gpio.GPIO_Speed = GPIO_Speed_100MHz;
	gpio.GPIO_OType = GPIO_OType_PP;
	gpio.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_Init(GPIOA, &gpio);

	ADC_InitTypeDef ADC_InitStructure;
	ADC_CommonInitTypeDef adc_init;

	RCC_APB2PeriphClockCmd(RCC_APB2Periph_ADC1, ENABLE); ADC_DeInit();
	ADC_StructInit(&ADC_InitStructure);

	adc_init.ADC_Mode = ADC_Mode_Independent; adc_init.ADC_Prescaler = ADC_Prescaler_Div2;
	ADC_InitStructure.ADC_ScanConvMode = DISABLE;

	ADC_InitStructure.ADC_ContinuousConvMode = DISABLE;
	ADC_InitStructure.ADC_ExternalTrigConv = ADC_ExternalTrigConvEdge_None;

	ADC_InitStructure.ADC_DataAlign = ADC_DataAlign_Right;
	ADC_InitStructure.ADC_Resolution = ADC_Resolution_12b;

	ADC_CommonInit(&adc_init);
	ADC_Init(ADC1, &ADC_InitStructure);
	ADC_Cmd(ADC1, ENABLE);
}

void analizator_init(void) {
	Usart_Log("Analizator init\n");
	analizator_timer_init();
	analizator_adc_init();
}

u16 readADC1(u8 channel) {
	Usart_Log("Read ADC\n");
	ADC_RegularChannelConfig(ADC1, channel, 1, ADC_SampleTime_3Cycles);
	ADC_SoftwareStartConv(ADC1);
	while (ADC_GetFlagStatus(ADC1, ADC_FLAG_EOC) == RESET)
	{}
	return ADC_GetConversionValue(ADC1);
}

void check_cmd(uint8_t ch)
{
	Usart_Log("Check cmd\n");
	switch (ch) {
	case '1':
		mode_2_deinit();
		mode_1_init();
		state = MODE_1;
		break;
	case '2':
		mode_1_deinit();
		mode_2_init();
		state = MODE_2;
		break;
	default:
		break;
	}
}

void Usart_Log(uint8_t * buf)
{
	while(*buf != '\0') {
		USART_SendData(USART1, *buf);
        buf = buf + 1;
    }

}

